table 'gold v_bc_salesperson'
	lineageTag: 4e2b4a97-6d28-48ae-a088-2fe3e4b95196

	column Code
		dataType: string
		lineageTag: c07a1f6b-08c6-402c-942c-8ca3f113937b
		summarizeBy: none
		sourceColumn: Code

		annotation SummarizationSetBy = Automatic

	column KeyNoCode
		dataType: string
		lineageTag: 09e75291-82f0-444c-a9f3-462003cd2daa
		summarizeBy: none
		sourceColumn: KeyNoCode

		annotation SummarizationSetBy = Automatic

	column Name
		dataType: string
		lineageTag: 7527832c-0e98-44d3-97a5-900c8236cb97
		summarizeBy: none
		sourceColumn: Name

		annotation SummarizationSetBy = Automatic

	column Email
		dataType: string
		lineageTag: a38f653a-f2a5-46ae-a264-8bd2d2b42c8c
		summarizeBy: none
		sourceColumn: Email

		annotation SummarizationSetBy = Automatic

	column JobTitle
		dataType: string
		lineageTag: c88a46fb-bd52-43ae-8aab-21cbb9650ad9
		summarizeBy: none
		sourceColumn: JobTitle

		annotation SummarizationSetBy = Automatic

	column SupervisorCode
		dataType: string
		lineageTag: d578832a-625e-4b23-9058-9cb23ac35645
		summarizeBy: none
		sourceColumn: SupervisorCode

		annotation SummarizationSetBy = Automatic

	column LoadDate
		dataType: dateTime
		formatString: General Date
		lineageTag: 2c6c38d5-9c84-4796-a6c1-849f1c06811e
		summarizeBy: none
		sourceColumn: LoadDate

		annotation SummarizationSetBy = Automatic

	column Company
		dataType: string
		lineageTag: 22d9f69e-d700-4b62-b5c7-45b7a3b25a84
		summarizeBy: none
		sourceColumn: Company

		annotation SummarizationSetBy = Automatic

	column SalespersonName
		dataType: string
		lineageTag: f07606b6-9a50-4955-91e4-33a35e8109de
		summarizeBy: none
		sourceColumn: SalespersonName

		annotation SummarizationSetBy = Automatic

	partition 'gold v_bc_salesperson' = m
		mode: import
		source =
				let
				    Źródło = PostgreSQL.Database("10.0.13.24", "dwh"),
				    gold_v_bc_salesperson = Źródło{[Schema="gold",Item="v_bc_salesperson"]}[Data],
				    #"Wstawiony tekst przed ogranicznikiem" = Table.AddColumn(gold_v_bc_salesperson, "SalespersonName", each Text.BeforeDelimiter([Email], "@"), type text),
				    #"Zamieniono wartość" = Table.ReplaceValue(#"Wstawiony tekst przed ogranicznikiem","p.lachmanski@zymetric.pl","r.fijalkowski@hvacbp.pl",Replacer.ReplaceText,{"Email"})
				in
				    #"Zamieniono wartość"

	annotation PBI_NavigationStepName = Nawigacja

	annotation PBI_ResultType = Table

