table 'gold v_bc_customers'
	lineageTag: 42ac4518-5dd2-4ee6-a060-dc62dff4fc75

	column NoCustomer
		dataType: string
		lineageTag: 610eb0ed-004d-4420-af38-5a9686f85397
		summarizeBy: none
		sourceColumn: NoCustomer

		annotation SummarizationSetBy = Automatic

	column KeyNoCustomer
		dataType: string
		lineageTag: cadf0cf8-c48b-4382-b14e-10acdc4b7202
		summarizeBy: none
		sourceColumn: KeyNoCustomer

		annotation SummarizationSetBy = Automatic

	column ContactType
		dataType: string
		lineageTag: 1de98066-364d-429c-b666-ea254747de7c
		summarizeBy: none
		sourceColumn: ContactType

		annotation SummarizationSetBy = Automatic

	column Name
		dataType: string
		lineageTag: 0efd1ee7-734b-4473-b2fd-804bd3ece4c7
		summarizeBy: none
		sourceColumn: Name

		annotation SummarizationSetBy = Automatic

	column Name2
		dataType: string
		lineageTag: cb2a52eb-68d2-4928-a49b-d0c835e476f7
		summarizeBy: none
		sourceColumn: Name2

		annotation SummarizationSetBy = Automatic

	column PartnerCode
		dataType: string
		lineageTag: 42dd95c5-e90a-4fa2-985a-033febfd2ef0
		summarizeBy: none
		sourceColumn: PartnerCode

		annotation SummarizationSetBy = Automatic

	column BalanceLCY
		dataType: double
		lineageTag: 2f09871d-ab22-4562-882f-368076b3b853
		summarizeBy: none
		sourceColumn: BalanceLCY

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column BalanceDueLCY
		dataType: double
		lineageTag: 5cf18c7f-b5f3-4412-b978-1a1e0441a65c
		summarizeBy: none
		sourceColumn: BalanceDueLCY

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CreditLimitLCY
		dataType: double
		lineageTag: 3fa8226c-da6d-48ed-98af-b10b85994caa
		summarizeBy: none
		sourceColumn: CreditLimitLCY

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Salesperson_Code
		dataType: string
		lineageTag: 0f82f37d-15d8-49bb-b7ba-5aa59d98adaf
		summarizeBy: none
		sourceColumn: Salesperson_Code

		annotation SummarizationSetBy = Automatic

	column TotalSales
		dataType: double
		lineageTag: 0b8c3c7e-58e2-4882-8a08-df4671657eb2
		summarizeBy: none
		sourceColumn: TotalSales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column VIP
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: e04bff19-502b-44fb-8120-ae12217df059
		summarizeBy: none
		sourceColumn: VIP

		annotation SummarizationSetBy = Automatic

	column CompanyProfile
		dataType: string
		lineageTag: 98ff81cf-e401-49cd-9161-3de18c078303
		summarizeBy: none
		sourceColumn: CompanyProfile

		annotation SummarizationSetBy = Automatic

	column CompanySegmentA
		dataType: string
		lineageTag: 90b80c4e-41a0-4c05-87eb-a9904d53907f
		summarizeBy: none
		sourceColumn: CompanySegmentA

		annotation SummarizationSetBy = Automatic

	column MagentoID
		dataType: int64
		formatString: 0
		lineageTag: 4ba26391-4ba9-4680-9355-d755d7ca018f
		summarizeBy: none
		sourceColumn: MagentoID

		annotation SummarizationSetBy = Automatic

	column ReckoningLimitLCY
		dataType: double
		lineageTag: 14ad8787-7c96-420b-829d-386140dc04c5
		summarizeBy: none
		sourceColumn: ReckoningLimitLCY

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column UsedLimitLCY
		dataType: double
		lineageTag: 241571a5-5640-402d-a1bd-9e662c54fe83
		summarizeBy: none
		sourceColumn: UsedLimitLCY

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column FactoringReckoning
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: f1c614b5-86aa-464d-8e90-69b334f3e529
		summarizeBy: none
		sourceColumn: FactoringReckoning

		annotation SummarizationSetBy = Automatic

	column InsuranceCustomer
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: adf66a6b-c770-42b6-a97c-8082ba0657b6
		summarizeBy: none
		sourceColumn: InsuranceCustomer

		annotation SummarizationSetBy = Automatic

	column LimitAmountInsurLCY
		dataType: double
		lineageTag: d2440000-6693-4552-87d6-d55edd54e1e0
		summarizeBy: none
		sourceColumn: LimitAmountInsurLCY

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CountryRegionCode
		dataType: string
		lineageTag: 04fd2ab1-31e8-42a8-a1a9-dc2ad86425b9
		summarizeBy: none
		sourceColumn: CountryRegionCode

		annotation SummarizationSetBy = Automatic

	column Address
		dataType: string
		lineageTag: 82db162e-0015-48fd-a0aa-1ab240d10d99
		summarizeBy: none
		sourceColumn: Address

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: 25ca5502-31cc-4d20-ac39-5c1c76a9f4c2
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column County
		dataType: string
		lineageTag: 45b91541-0e03-4cd2-9ae7-d518f526a47e
		summarizeBy: none
		sourceColumn: County

		annotation SummarizationSetBy = Automatic

	column PostCode
		dataType: string
		lineageTag: 5fd93713-c8ad-4ba0-a2d7-95e1aa372355
		summarizeBy: none
		sourceColumn: PostCode

		annotation SummarizationSetBy = Automatic

	column VATRegistrationNo
		dataType: string
		lineageTag: 577c3dfc-7bad-437f-9300-9512e1036d6c
		summarizeBy: none
		sourceColumn: VATRegistrationNo

		annotation SummarizationSetBy = Automatic

	column GenBusPostingGroup
		dataType: string
		lineageTag: 3abca69c-c36f-4f6d-9858-5bb225b50948
		summarizeBy: none
		sourceColumn: GenBusPostingGroup

		annotation SummarizationSetBy = Automatic

	column PaymentTermsCode
		dataType: string
		lineageTag: 1925c54a-61ea-49bb-97ae-5f12a5bdd2f9
		summarizeBy: none
		sourceColumn: PaymentTermsCode

		annotation SummarizationSetBy = Automatic

	column PaymentMethodCode
		dataType: string
		lineageTag: e4420776-b808-46b6-a830-9bc0bb652015
		summarizeBy: none
		sourceColumn: PaymentMethodCode

		annotation SummarizationSetBy = Automatic

	column LoadDate
		dataType: dateTime
		formatString: General Date
		lineageTag: 14d1b13e-13ff-4334-aaa0-e3eedd607b63
		summarizeBy: none
		sourceColumn: LoadDate

		annotation SummarizationSetBy = Automatic

	column Company
		dataType: string
		lineageTag: 8de0bf69-e00a-464e-b424-8d4ba1afc218
		summarizeBy: none
		sourceColumn: Company

		annotation SummarizationSetBy = Automatic

	column E_Mail
		dataType: string
		lineageTag: b390aade-7924-47d4-927f-f4b9da6ff328
		summarizeBy: none
		sourceColumn: E_Mail

		annotation SummarizationSetBy = Automatic

	column Phone_No
		dataType: string
		lineageTag: e5434660-5ad7-4fe2-81d7-33014cba01f1
		summarizeBy: none
		sourceColumn: Phone_No

		annotation SummarizationSetBy = Automatic

	partition 'gold v_bc_customers' = m
		mode: import
		source =
				let
				    Źródło = PostgreSQL.Database("10.0.13.24", "dwh"),
				    gold_v_bc_customers = Źródło{[Schema="gold",Item="v_bc_customers"]}[Data],
				    #"Zamieniono wartość" = Table.ReplaceValue(gold_v_bc_customers,"HURTOWNIA_WLASNA","HURTOWNIA WŁASNA",Replacer.ReplaceText,{"CompanyProfile"})
				in
				    #"Zamieniono wartość"

	annotation PBI_NavigationStepName = Nawigacja

	annotation PBI_ResultType = Table

